#import numpy as np
#import seaborn as sns
#import matplotlib.pyplot as plt

import pandas as pd

dataset = pd.read_csv("nyc-rolling-sales.csv")

##print my first 5 row
print(dataset.head())

##sort by SALE PRICE
print(dataset.sort_values('SALE PRICE'))

##check for missing values
print(dataset.isnull().sum())

## fill the missing values with 0
cleaned_data = dataset.fillna(0)
print(cleaned_data.isnull().sum())

## drop duplicates based on column
drop_duplicates = dataset.drop_duplicates(subset=['NEIGHBORHOOD'])
print(dataset.shape,drop_duplicates.shape)

## Sample DataFrame
df = pd.DataFrame({'BUILDING' : ['A1','A1','B1','B1','B1','B9','C0','C0','C0','C0','C0'],
                   'ZIP CODE' : [10457, 10458, 10457, 10457, 10457, 10458, 10458, 10458, 10458, 10457, 10457],
                   'RESIDENTIAL UNITS' : [1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3]})
print(df)

## looping
BUILDING = ['A1','A1','B1','B1','B1','B9','C0','C0','C0','C0','C0']
for BUILDING in BUILDING:
    print(BUILDING)

Data = dataset
for Data in Data:
    print(Data)

Data = dataset
for x in dataset:
    if x == 'SALES PRICE':
        continue
        print(x)

Data = dataset
for x in dataset:
    if x == 'corey':
        continue
        print(x)
    else:
        print('NA')

## Merging DataFrames
##Create DataFrame 1
df1 = pd.DataFrame({'BUILDING' : ['A1','A1','B1','B1','B1','B9','C0','C0','C0','C0','C0'],
                   'RESIDENTIAL UNITS' : [1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3]})
print(df1)

##Create DataFrame 2
df2 = pd.DataFrame({'BUILDING' : ['A1','A1','B1','B1','B1','B9','C0','C0','C0','C0','C0'],
                   'ZIP CODE' : [10457, 10458, 10457, 10457, 10457, 10458, 10458, 10458, 10458, 10457, 10457]})
print(df2)

##Merge DataFrame
df3 = pd.merge(df1,df2, on='BUILDING')
print(df3)

## List of strings
NYC = ['BOROUGH', 'NEIGHBORHOOD', 'BUILDING', 'BLOCK',  'ADDRESS']


# Define generator function get_lengths
def get_lengths(input_lists):

    #Yield the length of a string
    for word in input_lists:
        yield len(word)

#print the values generated by get_lengths()
for value in get_lengths(NYC):
    print(value)

##Create a list comprehension
RESIDENTIAL_UNITS = [[1, 1, 2,
                     2, 2, 2,
                     3, 3, 3]]
squares_RESIDENTIAL_UNITS = [[col for col in range (3)] for row in range(3)]

##Print squares_RESIDENTIAL_UNITS
for row in squares_RESIDENTIAL_UNITS:
    print(row)

import numpy as np
##calculate monthly rate for mortgage loan for 25 years, amount is $6625000 at 5% annual interest rate
monthly_rate = ((1+0.05)**(1/12) - 1)
print(monthly_rate)


##Plot the histogram
import matplotlib.pyplot as plt
df = pd.DataFrame({'RESIDENTIAL_UNITS' : (5,28,16,10,6,20,8,44,15,24,30,10)})

plt.hist(df['RESIDENTIAL_UNITS'])

#Label the axes
plt.xlabel('column')
plt.ylabel('row')

#show the figure
plt.show()

#Tidy up histogram chart
plt.hist(df['RESIDENTIAL_UNITS'], bins=30)

#Label the axes
plt.xlabel('column')
plt.ylabel('row')

#show the figure
plt.show()




